[package]
name = "singboard-service"
version = "1.2.0"
edition = "2024"

[lib]
name = "singboard_service"

[build-dependencies]
embed-resource = "3"

[dependencies]
windows-service = "0.7"
winreg = "0.55"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
tokio = { version = "1", features = ["rt", "net", "time", "io-util", "sync", "macros"] }
windows-sys = { version = "0.59", features = ["Win32_Foundation", "Win32_Security", "Win32_Security_Authorization", "Win32_System_Threading", "Win32_System_Pipes", "Win32_System_Memory", "Win32_Storage_FileSystem"] }
